language: cpp

matrix:
  include:
    - name: docker qbs clang8
      os: linux
      services:
        - docker
      script:
        - docker run -t -v${PWD}:/build -e TERM=xterm-color -e GTEST_COLOR=yes
            arbmind/qbs-clang8:1
            build --file /build/rec_cpp.qbs --build-directory /tmp/build
            -p autotest-runner
            modules.cpp.commonCompilerFlags:-fcolor-diagnostics

    - name: qbs msvc2017
      os: windows
      install:
        - choco install qbs
        - qbs setup-toolchains --detect
      script:
        - qbs
            build profile:MSVC2017-x64 --file rec_cpp.qbs --build-directory ${TMP}/build
            -p autotest-runner

#    - name: qbs msvc2019
#      os: windows
#      install:
#        - choco install qbs visualstudio2019buildtools visualstudio2019-workload-vctools
#        - qbs setup-toolchains --detect
#      script:
#        - qbs
#            build profile:MSVC0-x64 --file rec_cpp.qbs --build-directory ${TMP}/build
#            -p autotest-runner
